# Generated by Django 6.0.1 on 2026-02-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentname', models.CharField(max_length=150)),
                ('rollnumber', models.IntegerField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
