# Generated by Django 6.0.1 on 2026-02-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollnumber',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
